#!/bin/sh

# Dont use unicode
export LC_ALL=C
export LANG=C

## Variable
distro="$(cat /etc/os-release | cut -d'"' -f 2 | head -n1)"
arch="$(uname -m)"
kernel="$(uname -r)"
wm="${XDG_CURRENT_DESKTOP#*:}"
shell="${SHELL##*/}"
packages="$(pacman -Qq | wc -l)"
uptime="$(uptime -p | cut -b 4-22 | sed 's/minutes/mins/g')"

## Colors
magenta="\e[35m"
green="\e[32m"
white="\e[37m"
blue="\e[34m"
red="\e[31m"
black="\e[40;30m"
yellow="\e[33m"
cyan="\e[36m"

whitebold="\e[1;37m"
bluebold="\e[1;34m"
reset="\e[0m"

## Print Fetch

echo -e "\e[1m                   ${blue}$(whoami)..."
echo -e "${bluebold}        /\\         ${white}────────────"
echo -e "${bluebold}       /  \\        ${red}██ Distro: ${reset}$distro $arch"
echo -e "${bluebold}      /\\   \\       ${green}██ Kernel: ${reset}$kernel"
echo -e "${whitebold}     /      \\      ${yellow}██ WM: ${reset}$wm"
echo -e "${whitebold}    /   ,,   \\     ${blue}██ Shell: ${reset}$shell 5.8"
echo -e "${whitebold}   /   |  |   \\    ${magenta}██ Packages: ${reset}$packages (pacman)"
echo -e "${whitebold}  /_-''    ''-_\\   ${cyan}██ Uptime: ${reset}$uptime \n"
echo -e "                   ${black}████${red}████${green}████${yellow}████${blue}████${magenta}████${cyan}████${white}████${reset}\n"
